### ISSUE TITLE
Improve the readme.md 

### ISSUE THREAD

**Issue by rishabhrathore055** [Abipravi1/Hacktoberfest2022-python#148]

**Comment by pravee42** [comment]
Do it

**Comment by rishabhrathore055** [comment]
!
![image](https://user-images.githubusercontent.com/77366500/193817489-301328ac-0814-46dc-a003-20fe4a155e08.png)

**Comment by rishabhrathore055** [comment]
@pravee42 
Please accept the pull request.

**Comment by pravee42** [comment]
Accepted bro
