### ISSUE TITLE
EXCLUDED REPOSITORY

### ISSUE THREAD

**Issue by akash-rajak** [Abipravi1/Hacktoberfest2022-python#175]
This Respository is excluded from Hacktoberfest 2022.

**Comment by pravee42** [comment]
Recheck

**Comment by akash-rajak** [comment]
yes its excluded

check below image

![image](https://user-images.githubusercontent.com/57003737/194687167-2e9fc4b6-24c2-4137-a376-b2086c3a7661.png)

**Comment by pravee42** [comment]
IDK why it is showing like this we will fix this soon

**Comment by pravee42** [comment]
try another PR

**Comment by akash-rajak** [comment]
Ok let me do one more pull request and let see what happens

**Comment by akash-rajak** [comment]
Hi,
Its excluded, I did one PR again, and its showing same.

![image](https://user-images.githubusercontent.com/57003737/194706027-a5e7a5b3-065b-4957-9be1-8cfdfd10d35f.png)
