### ISSUE TITLE
If your PR has been accepted then comment 😁️ else 🤣️

### ISSUE THREAD

**Issue by pravee42** [Abipravi1/Hacktoberfest2022-python#8]

**Comment by Flash007-alt** [comment]
🤣️

**Comment by Flash007-alt** [comment]
can u pls guide me on the steps on how to submit my pr's pls

**Comment by pravee42** [comment]
sure

**Comment by pravee42** [comment]
- [ ] fork this repository
- [ ] git clone --depth 1 https://github.com/<your_github_user_name>/Hacktoberfest2021-python.git
- [ ] cd Hacktoberfest2021-python
- [ ] git remote add upstream https://github.com/pravee42/Hacktoberfest2021-python.git
- [ ] git remote -v
- [ ] git pull upstream master

- **create a new branch so that you can upload the code**

- [ ] git checkout -b <your_branch_name>

- Add the code files inside the **Hacktoberfest2021-python** folder

- [ ] git add .
- [ ] git commit -m "commit message"
- [ ] git push -u origin <your_branch_name_entered_before>
- [ ]  To create a pull request, click on `compare and pull requests`. Please ensure you compare your feature branch to the desired branch of the repo you are suppose to make a PR to.
- [ ] Add appropriate title and description to your pull request explaining your changes and efforts done.
- [ ]  Click on `Create Pull Request`
- [ ] now you have successfully created an pull request

**Comment by JoeFurfaro** [comment]
😄

**Comment by Llambi** [comment]
😄

**Comment by pravee42** [comment]
> 🤣

Hey @Llambi we have accepted your PR can you please check it

for more contributions to more repos join this server
https://discord.gg/pSup8ZZV
